// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPlayList() {
  return window['go']['main']['App']['ClearPlayList']();
}

export function GetPlayList() {
  return window['go']['main']['App']['GetPlayList']();
}

export function Invert(arg1) {
  return window['go']['main']['App']['Invert'](arg1);
}

export function OrderByDuration(arg1, arg2) {
  return window['go']['main']['App']['OrderByDuration'](arg1, arg2);
}

export function OrderByPopularity(arg1, arg2) {
  return window['go']['main']['App']['OrderByPopularity'](arg1, arg2);
}

export function OrderByYear(arg1, arg2) {
  return window['go']['main']['App']['OrderByYear'](arg1, arg2);
}

export function OrderPlayList(arg1, arg2) {
  return window['go']['main']['App']['OrderPlayList'](arg1, arg2);
}

export function PutSong(arg1) {
  return window['go']['main']['App']['PutSong'](arg1);
}

export function RandomPlayList() {
  return window['go']['main']['App']['RandomPlayList']();
}

export function RemoveSong(arg1) {
  return window['go']['main']['App']['RemoveSong'](arg1);
}

export function SearchSongInIndexInvert(arg1) {
  return window['go']['main']['App']['SearchSongInIndexInvert'](arg1);
}

export function SearchSongInTrie(arg1) {
  return window['go']['main']['App']['SearchSongInTrie'](arg1);
}
